services:
  - type: static
    name: portfolio
    env: static
    buildCommand: npm install && npm run build
    publishDir: out
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
